name: docker-image-release

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{GITHUB_REF##*/}}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/limpidchart/lc-renderer:${{IMAGE_TAG}}
            ghcr.io/limpidchart/lc-renderer:latest
