name: docker-image-develop

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/limpidchart/lc-renderer:${{ github.sha }}
            ghcr.io/limpidchart/lc-renderer:develop
