name: docker-image

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/limpidchart/lc-renderer:${{ github.ref }}
            docker.pkg.github.com/limpidchart/lc-renderer:latest
